apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: tanzu-wld-java-web-app
  description: Java Web App
  tags:
    - app-accelerator
    - java
    - spring
    - web
  annotations:
    'backstage.io/kubernetes-label-selector': 'app.kubernetes.io/part-of=tanzu-wld-java-web-app'
    'backstage.io/kubernetes-namespace': team1-dev
spec:
  type: service
  system: customer-service
  lifecycle: experimental
  owner: team1
