apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: tanzu-wld-java-web-app
  namespace: team1-dev
  labels:
    apps.tanzu.vmware.com/workload-type: web
    apps.tanzu.vmware.com/has-tests: true
    app.kubernetes.io/part-of: tanzu-wld-java-web-app
spec:
  params:
  - name: testing_pipeline_matching_labels 
    value:
      apps.tanzu.vmware.com/pipeline: test
      apps.tanzu.vmware.com/language: java
  source:
    git:
      ref:
        branch: main
      url: https://github.com/billglover/tanzu-wld-java-web-app
